import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google' 
import { HomeSections } from '@/Components/HomeSections/HomeSections'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Elite Blue Technoligies</title>
        <meta name="description" content="Generated by Elite Blue Technoligies" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSections />
    </>
  )
}
